### PR TITLE
Fix container state as string according to Docker spec

### LINKED ISSUE #63: Invalid state.status = "Up"
Hi and thanks for this project! On to the issue:

When inspecting a container via kubedock e.g.

```
$ curl -s localhost:2475/containers/07d501f99c5a190c9526ec1e08413532074df571a1428374f3dca73d810f54eb/json | jq
```

the "State" fragment says:

```
 "State": {
    "Dead": false,
    "Error": "",
    "ExitCode": 0,
    "FinishedAt": "0001-01-01T00:00:00Z",
    "Health": {
      "Status": "healthy"
    },
    "OOMKilled": false,
    "Paused": false,
    "Restarting": false,
    "Running": true,
    "StartedAt": "2023-12-18T16:34:46Z",
    "Status": "Up"
  }
```

But "Status: "Up" is not a valid value...
( https://github.com/joyrex2001/kubedock/blob/542618100bbf4766f449f35105ccbb1f95455f17/internal/model/types/container.go#L220-L234 )

Valid values are: "created" "running" "paused" "restarting" "removing" "exited" "dead" (ref https://docs.docker.com/engine/api/v1.43/#tag/Container/operation/ContainerInspect )

For example this makes the [dotnet testcontainers code parse the status as "undefined"](https://github.com/testcontainers/testcontainers-dotnet/blob/e3be24f8256c21be4525e8abae623695c8bb7fb2/src/Testcontainers/Containers/DockerContainer.cs#L169-L176) which means it polls the status indefinitely (personally I think it should crash, I might raise an issue with them too)

I imagine that other tools expecting valid values will show other issues.

### PR DESCRIPTION
**Pull request by mausch**
Fixes #63

~~I've not tested this tbh~~
I've just tested it, works as expected.

### CODE REVIEW

**Comment by joyrex2001** [comment]
Thanks!

**Comment by lpiepiora** [comment]
@joyrex2001 do you have ETA when this fix is going to be released, I'm actually hitting this problem (I'm using Rust's version of test containers and the library is trying to deserialise `Up`, which is not a valid state) & I was about to fix it myself, only to see it's already fixed in master ;)

**Comment by mausch** [comment]
FWIW if you have [Nix](https://github.com/DeterminateSystems/nix-installer#the-determinate-nix-installer) you can get the patched binary like this:

```
nix shell --impure --expr '
  let pkgs = (builtins.getFlake "github:nixos/nixpkgs/nixpkgs-unstable").legacyPackages."${builtins.currentSystem}"; in 
  pkgs.kubedock.overrideAttrs (f: p: { 
    src = pkgs.fetchFromGitHub {
        owner = "joyrex2001";
        repo = "kubedock";
        rev = "8b0fdde0a4374f1c336c8d436807690604c9c91c";
        hash = "sha256-W5M3ANPlVp202aRH5yCvUI2DSloe3h3qSstonGw4GuE=";
    };
  })'
```

**Comment by joyrex2001** [comment]
Released in: https://github.com/joyrex2001/kubedock/releases/tag/0.15.1

**Pull request merged**
